name: aims_mobile_app
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  card_settings: ^3.3.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  syncfusion_flutter_calendar: ^20.3.52

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
  assets:
    - assets/
